apiVersion: apps/v1
kind: Deployment
metadata:
  name: cecitd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cecitd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flask-cecitd
    spec:
      containers:
        - name: flask-cecitd
          image: 10.34.188.29/library/traffic:0.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 31001
      imagePullSecrets:
        - name: my-secret
