apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-cecitd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cecitd
  template:
    metadata:
      labels:
        app: flask-cecitd
    spec:
      containers:
        - name: flask-cecitd
          image: 10.34.188.29:5000/flask-cecitd
          imagePullPolicy: Always
          ports:
            - containerPort: 31001