apiVersion: v1
kind: Service
metadata:
  name: flask-cecitd-deployment
spec:
  type: NodePort
  ports:
    - name: cecitd
      targetPort: 5000
      port: 5000
      nodePort: 31001
  selector:
    app: flask-cecitd